# Generated by Django 3.0.5 on 2020-04-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=250)),
                ('meeting_date', models.CharField(max_length=250)),
                ('meeting_time', models.CharField(max_length=250)),
                ('meeting_location', models.CharField(max_length=250)),
                ('meeting_agenda', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'meeting',
                'db_table': 'meeting',
            },
        ),
    ]
