# Generated by Django 3.0.5 on 2020-05-01 02:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0003_resource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resource',
            new_name='Resources',
        ),
    ]
