# Generated by Django 3.0.5 on 2020-05-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20200501_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting_minutes',
            options={'verbose_name_plural': 'meeting minutes'},
        ),
        migrations.AlterModelOptions(
            name='resources',
            options={'verbose_name_plural': 'resources'},
        ),
        migrations.AlterModelTable(
            name='resources',
            table='resources',
        ),
    ]
