# Generated by Django 3.0.5 on 2020-05-01 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(default=datetime.date(2020, 5, 1)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.date(2020, 5, 1)),
        ),
    ]
