# Generated by Django 3.0.5 on 2020-05-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20200501_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.DateTimeField(),
        ),
    ]
