# Generated by Django 3.0.5 on 2020-05-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_auto_20200501_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
