# Generated by Django 3.0.5 on 2020-05-01 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0011_auto_20200501_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='meeting_minutes',
            name='attendance',
        ),
        migrations.AddField(
            model_name='meeting_minutes',
            name='attendance',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
