# Generated by Django 3.0.5 on 2020-05-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_auto_20200501_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='resources',
            name='date_entered',
            field=models.DateField(),
        ),
    ]
