# Generated by Django 3.0.5 on 2020-05-01 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_auto_20200501_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_time',
        ),
    ]
