# Generated by Django 3.0.5 on 2020-05-01 04:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_auto_20200430_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
