# Generated by Django 3.0.5 on 2020-05-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_meeting_meeting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_time',
        ),
    ]
