# Generated by Django 3.0.5 on 2020-05-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0018_meeting_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.CharField(max_length=250),
        ),
    ]
