# Generated by Django 3.0.5 on 2020-05-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0019_auto_20200430_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='date_entered',
            field=models.CharField(max_length=250),
        ),
    ]
