# Generated by Django 3.0.5 on 2020-05-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0021_remove_meeting_meeting_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_location',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_title',
        ),
    ]
