# Generated by Django 3.0.5 on 2020-05-01 05:24

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0022_auto_20200501_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting_minutes',
            options={},
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_location',
            field=models.CharField(default=datetime.datetime(2020, 5, 1, 5, 24, 8, 255751, tzinfo=utc), max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_title',
            field=models.CharField(default=4.1254125412541255e-05, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting_minutes',
            name='minutes_text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterModelTable(
            name='meeting_minutes',
            table=None,
        ),
    ]
